"""user have name

Revision ID: 11e48a78b97a
Revises: 2217d0d2f71f
Create Date: 2014-09-22 02:16:23.250591

"""

# revision identifiers, used by Alembic.
revision = '11e48a78b97a'
down_revision = '2217d0d2f71f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
