"""initial

Revision ID: 2217d0d2f71f
Revises: None
Create Date: 2014-09-21 23:17:24.414703

"""

# revision identifiers, used by Alembic.
revision = '2217d0d2f71f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipn_hash', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_ipn_hash'), 'users', ['ipn_hash'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_ipn_hash'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
