"""cache name in shadow

Revision ID: 452139bdd1d8
Revises: f339979e8fc
Create Date: 2014-10-09 00:13:52.093488

"""

# revision identifiers, used by Alembic.
revision = '452139bdd1d8'
down_revision = 'f339979e8fc'

from alembic import op
import sqlalchemy as sa

connection = op.get_bind()

userhelper = sa.Table(
    'users',
    sa.MetaData(),
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('name', sa.Text),
)
shadowhelper = sa.Table(
    'shadow',
    sa.MetaData(),
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('user_id', sa.Integer),
    sa.Column('name', sa.Text),
)
def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shadow', sa.Column('name', sa.String(), nullable=True))
    ### end Alembic commands ###
    for user in connection.execute(userhelper.select()):
        connection.execute(
            shadowhelper.update().where(
                shadowhelper.c.user_id == user.id
            ).values(
                name=user.name
            )
        )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shadow', 'name')
    ### end Alembic commands ###
