"""change ipn storage type

Revision ID: f339979e8fc
Revises: 349cbcdc83fa
Create Date: 2014-10-08 12:45:37.895917

"""

# revision identifiers, used by Alembic.
revision = 'f339979e8fc'
down_revision = '349cbcdc83fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ipn', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_users_ipn'), 'users', ['ipn'], unique=False)
    op.alter_column('users', 'ipn_hash', type_=sa.String(length=64))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_ipn'), table_name='users')
    op.drop_column('users', 'ipn')
    op.alter_column('users', 'ipn_hash', type_=sa.String(length=32))

    ### end Alembic commands ###
